package hyphen

import (
	"embed"

	"github.com/go-text/typesetting/language"
)

//go:embed dictionaries
var dictionaries embed.FS

var languages = map[language.Language]string{
	"af":      "dictionaries/af_za.dic",
	"af-za":   "dictionaries/af_za.dic",
	"be":      "dictionaries/be_by.dic",
	"be-by":   "dictionaries/be_by.dic",
	"bg":      "dictionaries/bg_bg.dic",
	"bg-bg":   "dictionaries/bg_bg.dic",
	"cs":      "dictionaries/cs_cz.dic",
	"cs-cz":   "dictionaries/cs_cz.dic",
	"da":      "dictionaries/da_dk.dic",
	"da-dk":   "dictionaries/da_dk.dic",
	"de":      "dictionaries/de_at.dic",
	"de-at":   "dictionaries/de_at.dic",
	"de-ch":   "dictionaries/de_ch.dic",
	"de-de":   "dictionaries/de_de.dic",
	"el":      "dictionaries/el_gr.dic",
	"el-gr":   "dictionaries/el_gr.dic",
	"en":      "dictionaries/en_gb.dic",
	"en-gb":   "dictionaries/en_gb.dic",
	"en-us":   "dictionaries/en_us.dic",
	"eo":      "dictionaries/eo.dic",
	"es":      "dictionaries/es.dic",
	"et":      "dictionaries/et_ee.dic",
	"et-ee":   "dictionaries/et_ee.dic",
	"fr":      "dictionaries/fr.dic",
	"gl":      "dictionaries/gl.dic",
	"hr":      "dictionaries/hr_hr.dic",
	"hr-hr":   "dictionaries/hr_hr.dic",
	"hu":      "dictionaries/hu_hu.dic",
	"hu-hu":   "dictionaries/hu_hu.dic",
	"id":      "dictionaries/id_id.dic",
	"id-id":   "dictionaries/id_id.dic",
	"is":      "dictionaries/is.dic",
	"it":      "dictionaries/it_it.dic",
	"it-it":   "dictionaries/it_it.dic",
	"lt":      "dictionaries/lt.dic",
	"lv":      "dictionaries/lv_lv.dic",
	"lv-lv":   "dictionaries/lv_lv.dic",
	"mn":      "dictionaries/mn_mn.dic",
	"mn-mn":   "dictionaries/mn_mn.dic",
	"nb":      "dictionaries/nb_no.dic",
	"nb-no":   "dictionaries/nb_no.dic",
	"nl":      "dictionaries/nl_nl.dic",
	"nl-nl":   "dictionaries/nl_nl.dic",
	"nn":      "dictionaries/nn_no.dic",
	"nn-no":   "dictionaries/nn_no.dic",
	"pl":      "dictionaries/pl_pl.dic",
	"pl-pl":   "dictionaries/pl_pl.dic",
	"pt":      "dictionaries/pt_br.dic",
	"pt-br":   "dictionaries/pt_br.dic",
	"pt-pt":   "dictionaries/pt_pt.dic",
	"ro":      "dictionaries/ro_ro.dic",
	"ro-ro":   "dictionaries/ro_ro.dic",
	"ru":      "dictionaries/ru_ru.dic",
	"ru-ru":   "dictionaries/ru_ru.dic",
	"sk":      "dictionaries/sk_sk.dic",
	"sk-sk":   "dictionaries/sk_sk.dic",
	"sl":      "dictionaries/sl_si.dic",
	"sl-si":   "dictionaries/sl_si.dic",
	"sq":      "dictionaries/sq_al.dic",
	"sq-al":   "dictionaries/sq_al.dic",
	"sr":      "dictionaries/sr.dic",
	"sr-latn": "dictionaries/sr_latn.dic",
	"sv":      "dictionaries/sv.dic",
	"te":      "dictionaries/te_in.dic",
	"te-in":   "dictionaries/te_in.dic",
	"th":      "dictionaries/th_th.dic",
	"th-th":   "dictionaries/th_th.dic",
	"uk":      "dictionaries/uk_ua.dic",
	"uk-ua":   "dictionaries/uk_ua.dic",
	"zu":      "dictionaries/zu_za.dic",
	"zu-za":   "dictionaries/zu_za.dic",
}
